CognitiveScale/cortex-cli

src/commands/skills.js, src/commands/utils.js
fix printSucess & printError to set color=on if no options specified
=> CCF-3810 Fix error handling in skill generator

README.md, bin/cortex-connections.js, bin/cortex.js, src/client/agents.js, src/client/connections.js, src/commands/connections.js
Connections additions. Test connections still needs some TLC.
=> Ccf 3975 cli connections

bin/cortex-agents.js, src/client/agents.js, src/client/catalog.js, src/commands/agents.js
* agents describe now has --versions option to fetch list of versions
* get-snapshots to fetch snapshots of an agent
* create-snapshot to create a snapshot of an agent
=> Ccf 4449 agents v2

bin/cortex-agents.js, src/client/agents.js, src/commands/agents.js
Implemented:
* Get agent instances
* Create agent instances
* Get agent instance
* Remove agent instance
* Stop agent instance
* Get list of triggers of current tenant
=> Ccf 4493 agent instances

bin/cortex-content.js, src/client/content.js, src/commands/content.js
* Upload secure content
* Download secure content
=> Ccf 4425 secret

bin/cortex-agents.js, bin/cortex-configure.js, bin/cortex-connections.js, bin/cortex-content.js, bin/cortex-datasets.js, bin/cortex-functions.js, bin/cortex-jobs.js, bin/cortex-processors.js, bin/cortex-project.js, bin/cortex-skills.js, bin/cortex-tasks.js, bin/cortex-types.js
This issue was raised by QA: CCF-4826.
=> doc the output type supported for the color option

bin/cortex-actions.js, bin/cortex.js, src/client/actions.js, src/commands/actions.js
=> Ccf 4827 actions

bin/cortex-accounts.js, bin/cortex.js, src/client/accounts.js, src/commands/accounts.js
Implemented: 
- `POST /accounts/groups`
- `GET /accounts/groups`
- `GET /accounts/groups/{groupName}`
- `DELETE /accounts/groups/{groupName}`
- `PUT /accounts/groups/{groupName}/members`
- `DELETE /accounts/groups/{groupName}/members`
- `POST /accounts/resources`
- `PUT /accounts/resources/{resourceName}/access`
**TODO** (when endpoints are functional):
- `GET /accounts/resources`
- `DELETE /accounts/resources`
- `DELETE /accounts/resources/{resourceName}/access`
=> Implemented CLI for Accounts v2 API (Groups, Resources)

bin/cortex-agents.js, bin/cortex-environments.js, bin/cortex.js, env.json, package-lock.json, package.json, src/client/agents.js, src/client/environments.js, src/commands/agents.js, src/commands/environments.js
=> Ccf 5022 env support

.npmrc, package.json
=> bump version to push latest generator-cortex 

package.json
https://github.com/CognitiveScale/generator-cortex/pull/18
=> Validation fixes

package.json
- Need to merge https://github.com/CognitiveScale/generator-cortex/pull/25/ prior to this
=> bumped `generator-cortex` version to `0.3.10`

bin/cortex-agents.js, src/client/agents.js, src/commands/agents.js
Merge after PR on cortex-agents!!!
=> Add environmentName option to list snapshots

bin/cortex-actions.js, package.json, src/client/actions.js, src/commands/actions.js
Daemons no longer take a list of ports, but rather just one port.
=> CCF-5792-daemon-lb

bin/cortex-actions.js, bin/cortex-agents.js, package.json, src/client/actions.js, src/client/agents.js, src/commands/actions.js, src/commands/agents.js
- Added environmentName option
- Also changed `ports` to `port` in `cortex actions`
=> Merging environmentName option to CLI

src/commands/configure.js
Minor cleanup so we ignore a trailing / on the url, and handle when the url is actually wrong but valid.
=> Cleanup handling when url isnt right on config

bin/cortex-agents.js, bin/cortex-environments.js, package.json, src/client/agents.js, src/client/environments.js, src/commands/agents.js, src/commands/environments.js
Added 'environments list-instances' command
Modified 'agents list-instances' command
Both commands support json, query options and return an array of instance objects.
=> Ccf 5462 list instances

.dockerignore, bin/cortex-accounts.js, bin/cortex-actions.js, bin/cortex-agents.js, bin/cortex-configure.js, bin/cortex-connections.js, bin/cortex-content.js, bin/cortex-datasets.js, bin/cortex-environments.js, bin/cortex-jobs.js, bin/cortex-processors.js, bin/cortex-project.js, bin/cortex-skills.js, bin/cortex-tasks.js, bin/cortex-types.js, bin/cortex-variables.js, bin/cortex.js, bin/utils.js, package.json, src/commander.js, src/commands/connections.js, src/commands/skills.js, src/compatibility.js, src/config.js, test/compatibility.js
I moved the "generate docs" and "if no command executed, show help and exit" stuff into a shared location (a monkey patch of the commander library).
Suggest you look `./src/commander.js` first.
=> Compatibility checks

bin/cortex-project.js
fixing import path.
https://cognitivescale.atlassian.net/browse/CCF-6914
=> fixing project generate command

src/commands/actions.js
conditionally overwriting params `properties` on daemon invocation
=> daemon-invocation-fix

bin/cortex-actions.js, package.json, src/client/actions.js, src/commands/actions.js
Encompasses CCF-7476, CCF-7451, CCF-6773
=> Ccf 7476 task status

bin/cortex-content.js, package.json, src/client/content.js, src/commands/connections.js, src/commands/content.js
... with additional progress bar goodness!
=> [CCF-7795] Managed content upload now uses streaming

bin/cortex-jobs.js, bin/cortex-tasks.js, bin/cortex.js
Will add clarification on the difference between v2 and v3 in the Cortex-cli reference documentation.
=> CCF-8270: Add v2 job descriptions.

bin/cortex-content.js, src/client/content.js, src/commands/content.js
Add new cli option to supply mimetype on upload
Enforce default value of application/octet-stream
=> CCF-8234 add --content-type to cortex content upload command

bin/cortex-actions.js, bin/cortex-content.js, bin/cortex.js, package.json, src/client/actions.js, src/client/content.js, src/commands/actions.js, src/commands/content.js
Add --content-type <MIME TYPE> option to `cortex content upload`
=> Release 0.12.3

package.json, src/commands/connections.js
pulls in the connections changes to generator: removes kerberos properties, adds advanced_jdbc type and plugin handling
=> CCF-8388 update generator-cortex version to 0.3.14

package.json
=> CCF-8388 v0.12.8

src/client/catalog.js, src/commands/agents.js
Just backing out the previous change
=> CCF-9783 reverting changes to agent and catalog

bin/cortex-actions.js, src/client/actions.js, src/commands/actions.js
=> Remove --timeout option from actions deploy

package.json, src/client/accounts.js, src/client/actions.js, src/client/agents.js, src/client/auth.js, src/client/catalog.js, src/client/connections.js, src/client/content.js, src/client/datasets.js, src/client/environments.js, src/client/jobs.js, src/client/tasks.js, src/client/variables.js, src/commands/apiutils.js, src/compatibility.js, test/client/compatibility.js, test/utils/api.js
` test/utils/api.js` and `commands/apiutils.js` are the most relevant/interesting changes
=> first working pass, seems like all client methods are now proxied

.gitignore, package.json, src/client/accounts.js, src/client/actions.js, src/client/agents.js, src/client/auth.js, src/client/catalog.js, src/client/connections.js, src/client/content.js, src/client/datasets.js, src/client/environments.js, src/client/jobs.js, src/client/tasks.js, src/client/variables.js, src/commands/agents.js, src/commands/apiutils.js, src/commands/content.js, src/commands/environments.js, src/commands/utils.js, src/compatibility.js, test/client/compatibility.js, test/utils/api.js
Release v0.12.15
1.  support for proxies.
2. Neil's addition / fix to list agent services
=> Release v0.12.15

src/commands/configure.js
=> Ccf 11021 validate configure

bin/cortex-actions.js, src/client/actions.js, src/commands/actions.js
=> Initial impl for getting logs from actions if the provider supports it

src/client/connections.js, src/commands/connections.js
=> CCF-11612 update based on review comments

bin/cortex-actions.js, package.json, src/client/actions.js, src/commands/actions.js
=> CCF-9044 add TTL option to actions deployment

package-lock.json, package.json
=> Bump js-yaml to 3.13.1 for https://nodesecurity.io/advisories/788

package-lock.json, package.json
=> version bump for lodash, set-value, mixin-deep

src/client/actions.js
=> Make cortex actions deploy --push-docker support/allow local images

package-lock.json, package.json
=> bumped generator version to `0.3.22`

bin/cortex-marketplace-agents.js, bin/cortex-marketplace-connections.js, bin/cortex-marketplace-datasets.js, bin/cortex-marketplace-skills.js, bin/cortex-marketplace.js, bin/cortex.js, package-lock.json, package.json, src/client/marketplace.js, src/commands/marketplace.js
This is a `merge --squash` of the MARK-777-generator-for-marketplace-resource-yaml-files onto latest cortex-develop
It has the advantage that it's more obvious what's going to happen and so easier to review - so suggest we review/merge this branch...
I also fixed package-lock.json so it has the right version of generator in it
=> Rebased marketplace commands and bump to v0.3.23

src/client/actions.js
Parsed 0 was resolving to false, isFinite will also check for NaN
=> CCF-11830 handle zeros in mem and vcpus

package-lock.json, package.json
=> bumped generator version to `0.3.24`

package-lock.json, package.json
=> Bump version to 0.12.19

package.json, src/compatibility.js, test/client/compatibility.js
=> CCF-12167 Change compatibility errors to warnings

bin/cortex-configure.js, package-lock.json, package.json, src/commander.js, src/config.js
=> Ccf 12859 cortextoken warning

.npmrc, package-lock.json, package.json
- [- ] Changes generate no new warnings 
This add a new warning/install error ...
=> CCF-12822 npm doesnot enforce anything, add preinstall check 

package-lock.json, package.json
=> bump version to 1.1.1

bin/cortex-deploy.js, bin/cortex.js, src/commands/deploy.js, src/commands/utils.js
=> FAB-30 Added deploy snapshot command to export agent snapshot and generate manifest file

src/commands/apiutils.js
Handle errors from cortex-auth bypassing redirect
Example response: Failed to describe profile : Auth Error: Cookie/header expired or malformed.
=> FAB-285 handle auth error

src/commands/apiutils.js, src/config.js
=> FAB-285 cleanup issuance, process env and token exp

bin/cortex.js
=> Remove dead commands, sort command help

bin/cortex-connections.js, bin/cortex-projects.js, bin/cortex-roles.js, bin/cortex-skills.js, bin/cortex-users.js, src/commands/projects.js
=> Added missing get aliases

bin/cortex-configure.js
=> FAB-177 error handling

bin/cortex-agents.js, package-lock.json, src/client/agents.js, src/commands/agents.js, src/compatibility.js
=> Add ability to export snapshot as a k8s agent + skills CRs

bin/cortex-roles.js, bin/cortex-users.js, package-lock.json, package.json, src/client/roles.js, src/client/users.js, src/commands/roles.js, src/commands/users.js
deny is no longer an action, moved to a flag
commands to assign/unassign roles/users to project
external group commands: list, describe, delete, and map to cortex role
=> FAB-342 deny action flag and external group commands

src/client/agents.js, src/commands/agents.js
=> fix travis build

src/client/apiServerClient.js
=> GQL type name changed from ProjectInput -> CreateProjectInput

src/commands/connections.js
=> fixing lodash commands for testing and saving a connection

c12e-ci.yml, src/commands/connections.js
=> Linting, node version bump

bin/cortex-profiles.js, bin/cortex-roles.js, bin/cortex-users.js
=> Only typos fixed in user facing commands help

src/commands/agents.js, src/commands/skills.js, src/commands/utils.js
=> Fix agent validation output

src/client/agents.js, src/commands/skills.js
=> invokeSkill fixes

bin/cortex-actions.js, src/client/actions.js, src/commands/actions.js, src/commands/agents.js, src/commands/skills.js
=> Fix undefined

bin/cortex-generate.js, bin/cortex-skills.js, package-lock.json, package.json, src/client/agents.js, src/commands/generate.js, src/commands/plopfile.js, src/commands/utils.js
=> Wasnot passing params, pass it and simplify request a bit

src/commands/utils.js
=> remove unquote

src/client/agents.js, src/commands/skills.js
=> FAB-673 Fix invoke skill JSON parse issue, fix skill save promise issue

src/commands/assets/templates/skill/external-api/skill.yaml.hbs
=> formatting changes for external-api skill type

src/commands/deploy.js
=> fixed undefined in export

src/commands/assets/templates/skill/daemon/skill.yaml.hbs
=> [FAB-715] added port properties

src/client/catalog.js
=> empty export file issue when campaign export failed

package-lock.json, package.json, src/client/catalog.js, src/commands/campaigns.js, src/commands/deploy.js
Merge back in 2.0.1-release branch to develop, prep for master merge
=> 2.0.1 release

bin/cortex-actions.js
=> Remove action invoke

bin/cortex-actions.js, package-lock.json, src/commands/actions.js
=> Support both --name and --actionName, sort options

src/commands/agents.js, src/commands/skills.js, src/commands/variables.js
=> improved error message for user input data

bin/cortex-campaigns.js
=> FAB-770 Help message fixes

src/client/actions.js, src/client/agents.js, src/client/catalog.js, src/client/connections.js, src/client/experiments.js, src/commands/agents.js
=> Added namespace removal changes

src/commands/assets/templates/skill/daemon/skill.yaml.hbs, src/commands/assets/templates/skill/external-api/skill.yaml.hbs, src/commands/assets/templates/skill/job/skill.yaml.hbs
=> Added namespace removal changes in skill generate template

src/client/experiments.js
=> Fixed unable to list experiments

src/commands/assets/templates/skill/job/README.md
=> job readme uses job command

src/commands/assets/templates/skill/daemon/Dockerfile, src/commands/assets/templates/skill/daemon/README.md, src/commands/assets/templates/skill/job/README.md
=> FAB-1159 Added actionName to docs, fixed workdir

bin/cortex-content.js
=> Added ls alias to content list

src/commands/assets/templates/skill/daemon/README.md, src/commands/assets/templates/skill/external-api/README.md, src/commands/assets/templates/skill/job/README.md
=> Fab 1171. FIxing the link to the skills docs

package.json
=> Version bump 2.0.1 -> 2.0.2

src/client/agents.js
=> FAB-1148: update list-activations command to use correct endpoint for v6

bin/cortex-agents.js, package-lock.json, src/client/agents.js, src/commands/agents.js
=> Added verbose flag to get-activation

src/client/content.js, src/commands/utils.js
=> FAB-1509 typo was causing to not resolve to correct base URL

bin/cortex-agents.js, bin/cortex-skills.js, src/client/catalog.js, src/commands/agents.js, src/commands/skills.js
=> Added version option for agents skills

bin/cortex-content.js, src/client/content.js, src/commands/content.js
=> [FAB-1509] Remove --secure option from content upload/download commands

src/client/actions.js, src/client/agents.js, src/client/catalog.js, src/client/connections.js, src/client/content.js, src/client/experiments.js, src/client/roles.js, src/client/users.js, src/client/variables.js
=> FAB-1587 Fix debug statements where the debug logs were not resolving the variables

bin/cortex-agents.js, src/client/agents.js, src/commands/agents.js
As of now, only the `--json` option works.. need to update the processing of the response for the pretty table (guess it wasn't updated after we decided to only list activationId's)
Here's the current output from a project in dci-dev:
```
clee@CS-0238 20:32:40 ~/projects/cortex5/cortex-cli  (FAB-1354)
$ cortex agents list-activations --project run-sh-dci daemon-test
┌──────────────────────────────────────┬────────────────────┬───────────────┬───────────────┬───────────────┬──────────────────────────────────────┐
│ Activation Id                        │ Type               │ Status        │ Start         │ End           │ Session Id                           │
├──────────────────────────────────────┼────────────────────┼───────────────┼───────────────┼───────────────┼──────────────────────── …
```
=> FAB-1354: rework agents list-activations command to allow for filtering options by state or time

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
=> Add skills deploy/undeploy cli commands

package-lock.json, src/client/catalog.js, src/client/secrets.js, src/commands/secrets.js
=> Secrets cli

bin/cortex-configure.js, bin/cortex-docker.js, src/commands/assets/templates/skill/job/skill.yaml.hbs, src/commands/docker.js
=> FAB-1753 : changed action output to match with outputs in skill

bin/cortex-actions.js, package-lock.json, package.json, src/commands/actions.js, src/commands/agents.js, src/commands/skills.js, src/commands/types.js, src/commands/utils.js, test/uploadDirectory.js
Make dates human readable,  add author
Add type list
- [X ] Notified docs of any potential USER-facing changes
- [X ] Added short description of the change - with relevant motivation and context. 
- [X ] Commented the code, particularly in hard-to-understand areas
- [X ] Ran `npm test` and it passes
=> Make columns consistent

src/commands/agents.js
=> FAB-1861 Fix for showing snapshot Id in the table

src/commands/agents.js
=> Fab 1782 fix snapshots

bin/cortex-actions.js, package-lock.json, package.json, src/client/actions.js, src/commands/actions.js
=> Remove actionType from action delete command, removed unneeded options

bin/cortex-actions.js, src/commands/actions.js
=> Add job timeout to action save, true up cli option to action file format

bin/cortex-agents.js, bin/cortex-configure.js, bin/cortex-skills.js, src/client/agents.js, src/client/catalog.js, src/commands/agents.js, src/commands/configure.js, src/commands/skills.js
=> Fab 1553 skill status

bin/cortex-models.js, bin/cortex.js, src/client/apiServerClient.js, src/client/models.js, src/commands/configure.js, src/commands/models.js
=> Fab 1848- cli commands for model crud

bin/cortex-assessments.js, bin/cortex.js, src/client/assessments.js, src/commands/assessments.js, src/commands/utils.js
=> impact assessment CLI integration

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
=> Use status from list skills REST api

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
=> FAB-976: adding commands to list skill action logs

bin/cortex-models.js, src/client/models.js, src/commands/models.js
=> support for tag filter in model list

package-lock.json
Please check you fulfil ALL of the relevant checkboxes
https://c12e.c1.io/go/tab/build/detail/cortex5-cli/336/build/1/Build
fix for the pipeline failure
=> npm audit fixes to fix the pipeline failure

bin/cortex-assessments.js, src/client/assessments.js, src/commands/assessments.js
=> list resource types API for assessments

bin/cortex-experiments.js, src/commands/experiments.js
=> renaming model id

src/commands/assessments.js
=> add missing semicolon causing build failure

bin/cortex-campaigns.js, bin/cortex-missions.js, bin/cortex.js, src/client/catalog.js, src/commands/campaigns.js
backend API issues:
* List mission response is in format { "0": {mission1 object}, "1": {mission2 obj}}. should be [{mission1}, {mission2}]
* `Created By`, `Created On` files are not there in list API
* List API returns empty for nonexisting campaign
=> FAB-2019 mission deploy and list API

src/commands/campaigns.js, src/commands/experiments.js
=> show startTime and took only if present

src/commands/assessments.js
=> dynamic table column width

bin/cortex-experiments.js, bin/cortex-models.js, src/client/experiments.js, src/commands/experiments.js
=> removed upload model command and improved create-run to accept json args

src/commands/assessments.js
=> null check

bin/cortex-models.js, src/commands/assessments.js
https://c12e.c1.io/go/pipelines/cortex5-cli/348/build/1
=> fixing build failures https://c12e.c1.io/go/pipelines/cortex5-cli/348/build/1

src/commands/assessments.js
=> format updated timestamp as moment

bin/cortex-missions.js, src/commands/campaigns.js
=> mission invoke command added

bin/cortex-experiments.js
=> fix for delete experiment failure

bin/cortex-configure.js, src/commander.js, src/commands/configure.js, src/config.js
=> Fix profile/profile options in env command

bin/cortex-agents.js, src/client/agents.js, src/commands/agents.js
=> Rollback activation list

package-lock.json, package.json, src/commands/experiments.js, src/commands/utils.js
=> remove tty-table and use cli-table3

bin/cortex-configure.js, src/commands/configure.js
=> Fix short ttl

src/client/catalog.js
=> FAB-1779 show campaign import warnings (missing secrets etc)

src/client/assessments.js, src/commands/assessments.js
=> dynamic table width and remove sorting from client side

src/commands/utils.js
=> remove empty lines

bin/cortex-assessments.js, src/client/assessments.js, src/commands/assessments.js
=> overwrite option in create assessment

bin/cortex-assessments.js, bin/cortex-deploy.js, package-lock.json, package.json, src/client/assessments.js, src/client/catalog.js, src/commands/assessments.js, src/commands/deploy.js
=> deploy campaign and connection command

src/client/assessments.js
=> encode names to handle /

src/client/assessments.js
=> uri encoding fix

bin/cortex-assessments.js
=> help text update

bin/cortex-campaigns.js, bin/cortex-missions.js, src/client/catalog.js, src/commands/campaigns.js
=> undeploy campaign and mission commands

bin/cortex-assessments.js, src/client/assessments.js, src/commands/assessments.js
=> typo fixes

src/client/assessments.js
=> url pattern conflict in catalog and phoenix

src/client/catalog.js
=> response binary data events handling improvement

src/commands/agents.js
```
/work/pipelines/cortex5-cli/src/commands/agents.js
54:39   warning  Assignment to property of function parameter 'd'         no-param-reassign
189:120  error    Expected to return a value at the end of arrow function  consistent-return
```
=> fixing build pipeline

package-lock.json, src/commands/agents.js
fix vulns
- [] Branch has the ticket number in its name (along with a ticket summary)
- [] Added tests that prove my fix is effective or that my feature works
=> Add title to get-activation report

package-lock.json, package.json
=> bump version to 2.0.5 for release and fix audit issues

bin/cortex-agents.js, bin/cortex-assessments.js, bin/cortex-campaigns.js, bin/cortex-deploy.js, bin/cortex-missions.js, package-lock.json, package.json, src/client/agents.js, src/client/assessments.js, src/client/catalog.js, src/commands/agents.js, src/commands/assessments.js, src/commands/campaigns.js, src/commands/content.js, src/commands/deploy.js, src/commands/models.js, src/commands/utils.js
=> CM-581 and Cortex Cli 2.0.5

bin/cortex-actions.js
Fixed typo in cli spec for commander..
=> FAB-2661 Fix --jobTimeout option

bin/cortex-agents.js, src/commands/agents.js
=> FAB-2640 add name to activation list output

bin/cortex-missions.js
=> Updated mission invoke command

bin/cortex-assessments.js, bin/cortex-deploy.js, src/client/assessments.js, src/client/content.js, src/commands/assessments.js, src/commands/deploy.js, src/commands/utils.js
=> Fab 2629 - MLOps and missing dependencies CLI

bin/cortex-missions.js
=> updated mission invoke agentname

cortex-cli.gocd.yaml
=> new gocd pipeline config

test/uploadDirectory.js
=> Fix bad directory name in uploadDirectory test

src/commands/assessments.js, src/commands/campaigns.js, src/commands/projects.js
=> commands options parsing fix

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
- [X ] Added short description of the change - with relevant motivation and context. 
- [X ] Commented the code, particularly in hard-to-understand areas
- [ X] Changes generate no new warnings
=> Add option to get skill as kubernetes resource to aid in debugging

src/commands/skills.js
=> fix skill output default

src/commands/deploy.js
=> fix as per changes in get skill response

src/commands/sessions.js
=> added tabular error for consistency

src/commands/experiments.js, src/commands/models.js
=> error handling

bin/cortex-sessions.js, package-lock.json, src/client/sessions.js, src/commands/sessions.js
=> added limit support to list sessions cli

src/commands/agents.js, src/commands/skills.js
=> fixed delete agents and skills

src/commands/sessions.js
=> change response message from "Session saved" to "Session <SessionId> created successfully""

src/commands/utils.js
=> testing build failure

src/commands/agents.js, src/commands/connections.js, src/commands/experiments.js, src/commands/models.js, src/commands/sessions.js, src/commands/skills.js, src/commands/utils.js
=> Fab 3528 Remove writeable from CLI connection list output and order by created

src/commands/users.js
=> returning just config

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
=> --json support for delete skill

bin/cortex-actions.js, bin/cortex-assessments.js, bin/cortex-campaigns.js, bin/cortex-configure.js, bin/cortex-connections.js, bin/cortex-content.js, bin/cortex-experiments.js, bin/cortex-projects.js, bin/cortex-roles.js, bin/cortex-secrets.js, bin/cortex-skills.js, bin/cortex-types.js, bin/cortex-users.js
=> added alias support to all the list clis

bin/cortex-skills.js, src/commands/skills.js
=> added podspec

src/commands/roles.js, src/commands/users.js, src/commands/utils.js
=> added tabular view to roles and users list cli

src/commands/experiments.js
=> removed promise resolve as it was always undefined

bin/cortex-missions.js
=> added list alias for missions

package-lock.json, package.json
=> FAB-3617 & FAB-3619: fix transitive dependency issues with mixin-deep and cache-base

bin/cortex-sessions.js
=> Fab 3623 change sessionname to session id for consistency

bin/cortex-tasks.js
=> fab-3695 adding alias for tasks list

src/client/users.js, src/commands/users.js
=> removing the pretty print of the jwt output and changed a few debug statements

src/commands/assets/templates/skill/daemon/README.md, src/commands/assets/templates/skill/daemon/make.bat, src/commands/assets/templates/skill/external-api/README.md, src/commands/assets/templates/skill/external-api/make.bat, src/commands/assets/templates/skill/job/README.md, src/commands/assets/templates/skill/job/make.bat
=> adding bat file for deployment on windows

package-lock.json, package.json, src/client/tasks.js, src/commands/roles.js, src/commands/users.js
=> Security fixes and debugging fix

package-lock.json, package.json
=> Revet plop 3.x -> 2.7.6 (esm)

src/commands/assets/templates/skill/job/Dockerfile
=> FAB-2024 Add scuttle to Dockerfile for jobs generated

src/client/info.js, src/config.js
=> added serverTs in token generation

bin/cortex-assessments.js, bin/cortex-missions.js, bin/cortex-secrets.js, src/commands/actions.js, src/commands/agents.js, src/commands/assessments.js, src/commands/campaigns.js, src/commands/connections.js, src/commands/content.js, src/commands/experiments.js, src/commands/models.js, src/commands/projects.js, src/commands/secrets.js, src/commands/sessions.js, src/commands/skills.js, src/commands/types.js, src/commands/utils.js
=> --query consistency in list clis

bin/cortex-assessments.js, bin/cortex-missions.js, bin/cortex-secrets.js, src/commands/actions.js, src/commands/agents.js, src/commands/assessments.js, src/commands/campaigns.js, src/commands/connections.js, src/commands/content.js, src/commands/experiments.js, src/commands/models.js, src/commands/projects.js, src/commands/secrets.js, src/commands/sessions.js, src/commands/skills.js, src/commands/types.js
=> JSME support bug

Dockerfile.c12e-ci.cortex-cli, README.md
=> Add run from source instructions

bin/cortex-configure.js, test/configure.js
=> re-enable tests

package-lock.json, package.json
=> bump package version to 2.0.8 for release

package-lock.json, package.json
=> bump package version to 2.0.8 for release (#511)

package-lock.json, package.json
=> Move preinstall -> prepare so it only runs for npm install "locally"

src/commands/agents.js
=> Add agentname

package-lock.json, package.json
=> Bump version 2.0.10 -> 2.0.11

src/commands/utils.js
=> allow checking for older sort options to be provided

src/commands/assets/templates/skill/job/Dockerfile
=> change scuttle image to use c12e maintained binary for job dockerfile

README.md, bin/cortex-projects.js, src/client/apiServerClient.js, src/commands/projects.js
=> [FAB-1907] Add Project delete command

package.json
=> bumping cli version

bin/cortex-skills.js, src/commands/tasks.js, test/tasks.js
=> FAB-4299 Typos fixed

src/commands/assets/templates/skill/daemon/Dockerfile, src/commands/assets/templates/skill/job/Dockerfile
- [x ] Added tests that prove my fix is effective or that my feature works
=> Use the slim python images as a default

src/client/content.js
=> added code to catch error

src/commands/workspaces/generate.js
This PR adds two template vars that were missing missing from the CLI generator.  These vars are supported in the IDE.  
TODO:  Modify the IDE to use the generate, build, and publish functionality from the CLI client library, to eliminate duplication of those functions.
=> Added missing template vars:  generatedFiles and template for CLI

src/commands/agents.js
This will fix the failing integration test.
=> switch offset back to skip for list-activations

package-lock.json, package.json, src/commands/agents.js
=> hotifx since 6.3.0 cli changes are merged for prgy

bin/cortex-roles.js
- [ x] Branch has the ticket number in its name (along with a ticket summary)
=> FAB-4534 fix duplicate alias for describing external roles

src/commands/workspaces/build.js, src/commands/workspaces/workspace-utils.js
=> Glob starting with / generates bad paths ... /my/path/my/path/skill.yaml

src/commands/workspaces/build.js, src/commands/workspaces/generate.js, src/commands/workspaces/workspace-utils.js
=> Fab 4607 - Handle incorrect template names specified

bin/cortex-workspaces.js, src/commands/workspaces/publish.js
=> Fab 4608 - Add --project option for publish command

bin/cortex-agents.js, bin/cortex-skills.js, src/commands/agents.js, src/commands/skills.js
=> Enhance Skill/Agent save to make it variadic

src/commands/workspaces/registry.js
=> FAB-4596 - Fixed workspace registry deletion

src/commands/skills.js
=> error if skill doesnt contain an action with applied podspec

bin/cortex-types.js
=> removed duplicate alias  

src/commands/workspaces/build.js, src/commands/workspaces/publish.js
=> FAB-4804 - Handle invalid skill name for publish, improved status output

src/commands/workspaces/publish.js
- [x ] Added short description of the change - with relevant motivation and context. 
- [x ] Added tests that prove my fix is effective or that my feature works
- [x ] Changes generate no new warnings
- [x ] Changes are backward compatible with older clusters
=> FAB-4785 - Fix issue with content publishing

bin/cortex-workspaces.js, src/commands/workspaces/registry.js
- [x ] Added short description of the change - with relevant motivation and context. 
- [x ] Added tests that prove my fix is effective or that my feature works
- [x ] Changes generate no new warnings
- [x ] Changes are backward compatible with older clusters
=> FAB-4815 - Fixed problems with adding and removing registries

src/commands/utils.js
The previous fix neglected the MIN size case.
=> FAB-4817 - Check for MIN name length

src/commands/workspaces/generate.js
Prevents generating a new skill over top of an existing one.
=> FAB-4626 - Dont allow skill generation over top of existing skill.

src/commands/experiments.js
=> Add duration plugin for dayjs to fix experiments list

src/client/catalog.js
- [x ] Changes generate no new warnings
- [ x] Changes are backward compatible with older clusters
=> FAB-5017 use the v6 agentinvoke endpoint

bin/cortex-content.js
=> update help text for cortex content download

bin/cortex-agents.js
=> FAB-5067 Make snapshot definition optional

src/commands/tasks.js
=> FAB-4992, FAB-4911 remove action column and expand name & skill name

bin/cortex-actions.js, package-lock.json, package.json, src/commands/tasks.js
- [ x] Branch has the ticket number in its name (along with a ticket summary)
- [x ] Changes are backward compatible with older clusters
=> Fab 5025 task limit

src/commands/experiments.js
=> FAB- 5079 fix epoch to date

bin/cortex-assessments.js
- [ x] Branch has the ticket number in its name (along with a ticket summary)
- [ x] Changes are backward compatible with older clusters
=> FAB-3694 fix naming, add alias for backward compatibility

src/commands/actions.js, src/commands/agents.js, src/commands/connections.js, src/commands/experiments.js, src/commands/models.js, src/commands/secrets.js, src/commands/skills.js, src/commands/utils.js, test/testUtils.js
Issue: https://cognitivescale.atlassian.net/browse/FAB-4315
=> Fab 4315 - Standardize failing with non-zero exit code when deleting resource with dependencies

src/config.js
=> Add warning if CORTEX_TOKEN used from env

src/commands/projects.js
=> FAB-4354 handle deleting same project

src/commands/agents.js
=> Fix for FAB-5252 to check existence of file

src/client/catalog.js
=> resolve need to passed correctly to be called by callback

src/commands/utils.js, src/commands/workspaces/configure.js, src/commands/workspaces/generate.js, src/commands/workspaces/publish.js, src/config.js, test/cortex/config, test/uploadDirectory.js
* Template config is now per-profile.  This increments the config file version to 5.
* Image tag displayed on successful publish.
* Fixed a broken test on Windows.
=> FAB-5346 and FAB-5347

src/commands/workspaces/build.js
=> Add newline, fix undefined

package-lock.json, src/commands/utils.js
=> vuln fix and handling messgaing

package-lock.json, src/commands/utils.js
=> Change the handleListFailure 

bin/cortex-missions.js
=> agent changes for single batch job in mission runtime

bin/cortex-missions.js
=> Single batch job

src/commands/workspaces/workspace-utils.js
=> Fix keytar import

src/commands/users.js
=> remove debug

src/client/secrets.js, src/commands/secrets.js
=> allow for proper response format {} not "Deleted"

src/commands/secrets.js
=> Fix delete message

src/commands/secrets.js
=> Fix message

bin/cortex-skills.js, src/client/catalog.js, src/commands/skills.js
=> fix skills logs, add support for raw logs, and better error reporting

package-lock.json, src/client/apiutils.js
=> Merge conflict

bin/cortex-agents.js, bin/cortex-tasks.js
=> remove the old asc and desc sort

src/commands/types.js
=> handling dependecy check for types delete

src/commands/types.js
=> fix incorrect logic

bin/cortex-agents.js, bin/cortex-skills.js, src/client/catalog.js, src/commands/agents.js, src/commands/skills.js, src/commands/utils.js
=> Add --output openapi to get skill and agent

bin/cortex-agents.js, bin/cortex-skills.js, src/commands/agents.js, src/commands/skills.js, src/commands/utils.js
=> Add -f --output-file to the cli for skills/agents get

package-lock.json, package.json
=> 6.4.1 version change

.github/workflows/package-binary.yaml
- need this to get latest builds to QA before merging to main
=> also build binary from develop

bin/cortex-pipelines-repos.js, bin/cortex-pipelines.js, src/client/pipelineRepositories.js, src/client/pipelines.js, src/commands/pipelineRepositories.js, src/commands/pipelines.js, test/pipelines.js
- added pipelinest list, describe commands
- fixed unit tests for pipeline repositories
- added unit tests for pipelines commands
=> FAB 6047 pipeline describe list

src/client/pipelines.js, test/pipelines.js
- fixed pipeline endpoint
- fixed server URL
=> fix pipelines url

bin/cortex-pipelines-repos.js, src/client/pipelineRepositories.js, src/commands/pipelineRepositories.js, test/pipelineRepositories.js
Issue: https://cognitivescale.atlassian.net/browse/FAB-6052
=> Fab 6052 - Add ability to update pipelines with custom Skill reference

bin/cortex-pipelines.js, src/client/pipelines.js, src/commands/pipelines.js
* added sha as optional param to describe pipeline
=> added sha as optional param to describe pipeline

src/client/catalog.js, src/commands/skills.js, src/commands/utils.js
=> Remove unneeded error handling, fix skill logs error output

bin/cortex-pipelines-repos.js, bin/cortex-pipelines.js, src/client/pipelines.js, src/commands/pipelines.js
- Describe pipeline run to only require runId
- pipelineRepoDefinition to be a required option
- fixed alias
- fixed alias for pipeline repos
=> FAB 6179 pipelines run

src/commands/pipelineRepositories.js, test/pipelineRepositories.js
CLI previously printing: `Failed to update repo pipelines`
Issue: https://cognitivescale.atlassian.net/browse/FAB-6277
=> FAB-6277: Report no changes made on Pipeline Update when no changes were made

src/commands/utils.js, test/testUtils.js
With this change, the catalog service PR shouldn't be needed.
=> handle TSOA API validation error responses
