bin/cortex-agents.js
src/client/agents.js
src/commands/agents.js
src/commands/utils.js

Made constructError utility more likely to produce something useful, particularly when response isn't JSON.
Added describe-snapshot subcommand, and tweaked list-snapshots to return agent version and not description (which is always empty).

Add describe-snapshot, clean up error handling

---

src/commands/agents.js
src/commands/environments.js
src/commands/utils.js

* Report detailed errors on snapshot promotion.
* Drop confusing/invalid --environmentName parameter when listing types, agents or skills
* Drop invalid fields (label, blacklist, whitelist) from environments list, and add region

Improve error messages and other cleanup to support Edge

---

.dockerignore
bin/cortex-accounts.js
bin/cortex-actions.js
bin/cortex-agents.js
bin/cortex-configure.js
bin/cortex-connections.js
bin/cortex-content.js
bin/cortex-datasets.js
bin/cortex-environments.js
bin/cortex-jobs.js
bin/cortex-processors.js
bin/cortex-project.js
bin/cortex-skills.js
bin/cortex-tasks.js
bin/cortex-types.js
bin/cortex-variables.js
package.json
src/commands/connections.js
src/commands/skills.js
src/compatibility.js
src/config.js
test/compatibility.js

Read it and weep :-(
`commander.js` usage of `process.spawn` for executing sub-commands makes it impossible for me to fetch the specified profile and run a compatibility check globally.  Rather than modifying every command's `execute()` method, I've kept the `/src/...` tree unaware of the checks, and instead created a Command.Action wrapper and is called by the cortex-* implementations in `/bin`.
I also made a few other cleanup changes (e.g. most of the generate commands didn't actually need a --profile options, etc.)

Add backend compatibility check to all commands which use a profile

---

bin/cortex-variables.js

Add missing `--json` option to `variables list` and `variables describe` commands.
NOTE: I'll `npm version patch && git push --tags && git push` in the develop branch after this is merged.

[CCF-6706] Add missing `--json` option to `variables` commands

---

bin/cortex-accounts.js
bin/cortex-actions.js
bin/cortex-agents.js
bin/cortex-connections.js
bin/cortex-content.js
bin/cortex-datasets.js
bin/cortex-environments.js
bin/cortex-jobs.js
bin/cortex-processors.js
bin/cortex-skills.js
bin/cortex-tasks.js
bin/cortex-types.js
bin/cortex-variables.js
src/compatibility.js

I'll bump to 0.9.0 after merged. Yes, I'm sad about how I had to implement this.

Add `--no-compat` option to bypass API compatibility checks

---

src/client/content.js
src/commands/content.js

Lets you download non-text content such as a zip, to stdout (which can be redirected to a file), using streaming. Will detect an error rather than treating the json returned by content API as if it was the downloaded content. Outputs errors and success message to stderr, so it doesnt interfere with redirecting content to a file.

Support streaming and non-text download of managed content

---

bin/cortex-docker.js
bin/cortex.js
package.json
src/commands/docker.js

Added `cortex docker login` command.
It performs a `docker login` against the Cortex registry using the
profile's JWT.

CCF-7909-cli-docker-login

---

bin/cortex-actions.js
package.json
src/client/actions.js
src/commands/actions.js

Added support for an actions deploy option in the following formats:
* --environmentVariables '"env.var"="Environment Variable", "my.env.var"="Hello World!"'
* --environmentVariables '"env.var":"Environment Variable", "my.env.var":"Hello World!"'
Actions describe returns the environment variables for the action if they exist.
Currently, environment variables is only supported for daemons.

CCF-8404 support environment variables for actions deploy

---

bin/cortex-content.js
package.json
src/commands/content.js
src/commands/utils.js
test/cortex/sample/upload/config
test/uploadDirectory.js

Now able to upload entire directory to our managed content:
Here is a shared example:
`cortex content upload .shared /Users/dwisecup/code/c5/ccf-9417/upload --recursive`
`
18.7K	conn_types/cdata_conn_types.json -> .shared/conn_types/cdata_conn_types.json
18.7K	conn_types/cdata_conn_types2.json -> .shared/conn_types/cdata_conn_types2.json
7.4M	drivers/cdata.jdbc.actcrm_18.0.6886.0.jar -> .shared/drivers/cdata.jdbc.actcrm_18.0.6886.0.jar
7.4M	drivers/cdata.jdbc.test_18.0.6886.0.jar -> .shared/drivers/cdata.jdbc.test_18.0.6886.0.jar
174B	keys/cdata_rtk.json -> .shared/keys/cdata_rtk.json
174B	keys/cdata_rtk2.json -> .shared/keys/cdata_rtk2.json
174B	keys/more_keys/cdata_rtk.json -> .shared/keys/more_keys/cdata_rtk.json
174B	keys/more_keys/even_more/keys/cdata_rtk.json -> …

working recursive upload of directory

---

bin/cortex-agents.js
src/client/agents.js
src/commands/agents.js

Allow user to query the list of instances for a snapshot. Optionally specify environmentName.
JSON-formatted response is similar to:
```
[
{
"instanceId": "5c7463e2d1ae6327d757c755",
"status": "started",
"snapshotId": "5335fda4-225d-434c-9e73-547178fc93e3",
"environmentName": "cortex/default",
"createdAt": "2019-02-25T21:53:38.934Z"
}
]
```
Table lists the above fields other than snapshotId.

Add `cortex agents list-snapshot-instances`

---

src/client/content.js

The error message wasn't being reported when content upload failed (because 'on response' is triggered before the body is available).

Return error message from content upload properly

---

src/client/content.js
src/commands/content.js
src/commands/utils.js

Fix handling of non-http errors, like network or filesystem issues
Fix error propagation from getSourceFiles() in callbacks errors are typically first.

Tweaks to error handling

---

bin/cortex-connections.js
package-lock.json
package.json
src/client/connections.js
src/commands/connections.js

Added a new command to query a connection.  Defaults to use 'select 1' if no query option is selected.  Was helpful in some of my testing so figured it may be a good addition to the cortex-cli.  Will update the package.json in a later commit once this goes through some iterations

CCF-11612 add connection query command

---

src/client/actions.js

Fix so it tolerates return of array of strings from API (for Rancher daemons) or the more standard `{ status: success, logs: [...] }` for k8s that is consistent with jobs.

Tolerate daemon logs as array or structured response

---

bin/cortex-actions.js
package.json
src/client/actions.js
src/commands/actions.js

Followed the same pattern as `memory` and `vcpus` (simple `_.isFinite` check, no validation of min/max, that it's only allowed for actionType daemon, etc.).  Too much of a PITA with commander.js to do anything fancier.

[CCF-11868] Add scaleCount option to action deploy

---

src/client/graph.js

The DELETE route in the graph service is `.../profiles/*` and requires a profile ID.  The CLI was using `.../profiles`, which is not the same route and is rejected by Express.
I'll do `npm version patch` in the develop branch after this is merged to bump the version.

[CCF-12231] Fix endpoint specification for deleting a profile

---

package-lock.json
package.json

Other deps are outdated (since we pin everything), but tty-table was the only one flagged by the audit.  I'll bump CLI version and tag after merge to develop.

[CCF-12390] Update deps to pass audit

---

src/commands/actions.js

Remove odd behavior invoking agents,  the api endpoint is provided from the cli's profile and NOT using the internal cluster address.  This has unintended consequences when using proxies/etc..

Fix api end

---

bin/cortex-configure.js
bin/cortex-roles.js
src/commands/configure.js
src/config.js

This was duplicated functionality from `cortex users describe --roles` and was meant to be removed.
Piggy backed a nice to have `cortex configure token [--profile]` gets a PAT with 1 day expiration.

FAB-177 remove list roles by user

---

src/commands/deploy.js

describe agent snapshot is returning JSON but earlier it was returning response, this broke deploy snapshot. Fixing this with updated agent describe snapshot

updated deploy snapshot as per updated agent describe snapshot

---

src/commands/assets/templates/skill/daemon/README.md
src/commands/assets/templates/skill/external-api/README.md
src/commands/assets/templates/skill/job/README.md

Revised the skill generate template readmes  to match (an abbreviated version) the v6 build-skills docs and to add links to those docs.
https://cognitivescale.atlassian.net/browse/FAB-1010

skill-generate  templates v6 updates

---

generate_docs.js

There may be a better way to fix this, but with this change, when you generate the docs using ` ./generate_docs.sh`, you don't have to make any changes to the `cortex-cli-docs.md` output before copying it to the cortex-fabric docs for use in the docusaurus site.
@jgielstra-cs - please feel free to tweak this if it doesn't make sense the way I did it. Thanks!
The main difference is below.
Before the change, `br`s in this section were inserted in code brackets (i.e. they would print out as `<br /` rather than inserting a break) and there were a bunch of `nbsp`s that were printed out as text, not as actual spaces. 
**Before:**
**After:**
And it looks fine when built in the docs now. The extra breaks and spaces weren't needed.

Fix docs gen

---

src/commands/plopfile.js

Can't explain why the old templateFiles specification worked on macOS but not on Windows.  Perhaps NodeJS path.join behavior on windows doesn't like {{}}?  This change empirically fixes things on my Win10 VM, and it continues to work correctly on macOS.

[FAB-1154] Fix node-plop template files glob pattern for Windows

---

bin/cortex-roles.js
src/parsers.js

NOTE: I didn't want to add explicit empty-string-checks directly in the command action handlers, and I wanted the console output to look very similar to other command arg processing errors handled by commander.
The program.[required]option() method can take a parser function, so I hooked into that and had the parser log and exit just like commander does internally.

When using the --users option of roles assign command ensure there are no empty strings

---

bin/cortex-roles.js
src/parsers.js

This is an alternative to https://github.com/CognitiveScale/cortex-cli/pull/319, and fixes my previous implementation of the empty string parser as it was intended to work.
Note: commander is always presenting each individual username to the parser, but the internal codepath in commander **only** calls a provided parser, and does **not** perform the array build-up.  (Behavior is "provided parser XOR regular/other handling").  See https://github.com/tj/commander.js/blob/release/6.x/index.js#L536
This PR changes the parser to take an additional `variadic` option, and performs the array build-up as linked above when true.  (Super lame the parser is not provided the Option, which prevents the parser from automatically determining variadic or not :-/ ).

[FAB-1689] Previous implementation of empty string parser did not handle variadic params

---

bin/cortex-configure.js
bin/cortex-docker.js
package-lock.json
package.json
src/commands/configure.js
src/commands/docker.js

- currently does a bit of string replace hackery to figure out the private-registry url, this can be fixed once the new info endpoint is available
- default ttl of token created for docker login is set to 14d but can be overridden (for long lived kube secrets.. not really reliable though if the JWK changes)

Fixing docker-login command to work with fabric endpoints

---

bin/cortex-users.js
src/client/users.js
src/commands/users.js

Wasn't sure if the `users` command was the right place to add these commands.. figured typical users would make a new service user (NOTE: trying to keep the verbiage different from being confused with k8s ServiceAccounts) and then immediately assign roles/grants to them?

FAB-1699: commands for creating/listing/deleting service users

---

src/client/assessments.js

encoding not required for request body params and null values will be converted to "undefined" cause them so save as valid value for required fields

encoding not required for request body params

---

build.sh
package-lock.json
package.json

add resolution field to package.json and `npx npm-force-resolutions` to preinstall script to force upgrades on transitive dependencies for cache-base and mixin-deep

FAB-3617 and FAB-3619: resolve security vulns for transitive deps on mixin-deep and cache-base

---

package-lock.json
src/config.js

This was introduced recently while trying to fix some of our [timing issues when generating tokens](https://github.com/CognitiveScale/cortex-cli/pull/481).
use system time as a default if info endpoint response does not include the server timestamp
also bumped packages from npm audit scan

compatibility issue found in dci-qa

---

src/commands/tasks.js

Remove JSON.stringify from task log output

---

bin/cortex-actions.js

mark actionDefinition as optional and any other small issues that pop up while fixing the integration tests.

Misc fallout from integration tests

---

bin/cortex-workspaces.js

The registry option for generate is no longer used, because the CLI/IDE automatically substitute the active registry at publish time.

FAB-4605 - Remove registry option for generate

---

bin/cortex-workspaces.js
src/commands/workspaces/generate.js

As requested in FAB-4606, the --notree option should behave like the --color option, meaning that you can specify true or false as a value.

Makes --notree work just like --color

---

src/commands/workspaces/build.js
src/commands/workspaces/publish.js

Build status should be shown correctly when build fails.

FAB-4838 - Show build status results correctly.

---

bin/cortex-tasks.js

- [ x] Branch has the ticket number in its name (along with a ticket summary)
- [x ] Changes generate no new warnings
- [x ] Changes are backward compatible with older clusters

FAB-4955 Make desc the default so newer (larger) starttime are at top

---

cortex-cli.gocd.yaml

add a new manually approved stage to develop pipeline to handle fast-forward merge up to main for a release
We can still use the PR's to review what's included in a release but now we should be able to rely on the pipeline to handle the merge for us (and also without taking the extra merge commit into main)

Pipeline stage to handle merge up to main

---

package.json

The types for Typescript need to be included in the distribution, so the IDE extension can use the package.

Forgot to include Typescript types

---

src/client/apiutils.js

Was relying on the `--debug` output for figuring out the request/response structures for the TSOA migration.. I thought `options.body` had been working for some commands but when trying to test some of the service user API's I was getting `{}` returned.

use options.json instead of body for printing debug output

---

src/commands/utils.js

The name validation code was completely broken after migration to esm probably. I got the regex from cortex-catalog

fix validation for workspaces generate

---

src/client/pipelineRepositories.js
test/pipelineRepositories.js

Catalog service is expecting skillName, not skill in query param

Fab 6167 skillname

---

bin/cortex-pipelines-repos.js
src/commands/pipelineRepositories.js
test/pipelineRepositories.js

Found a small bug where the PipelineRepoDefinition (file) is still required even if you use the convenience CLI flags. Added a unit test to prove the fix works and the command supports JSON & YAML
Related Issue: https://cognitivescale.atlassian.net/browse/FAB-6172

Support saving a Pipeline Repo using CLI flags without the definition file

---

src/commands/utils.js
test/testUtils.js

Changes:
* Handles error response from `cortex tasks lists` which doesn't include a period in the key.
```
{
status: 400,
details: {
type1: {
message: 'message1',
value: '-1',
},
},
}
```

fixed TSOA error response - key without period (.)
